name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  example:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Build example
        run: make build-example

  test-library:
    name: MacOS
    runs-on: macos-13
    strategy:
      matrix:
        xcode: ['15.0']
        config: ['debug']
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.8"
      - name: Swift Version
        run: swift --version
      - name: Download supabase
        run: brew install supabase
      - name: Start supabase
        run: supabase start
      - name: Run ${{ matrix.xcode }} Tests
        run: make CONFIG=${{ matrix.config }} test-library
